* FIX: the query introduced by commit 93d30e4e
the query won't work if the database used is postgres due to
type mistmacth in the where condition: lime_question_attributes.value=1

Since lime_question_attributes.value is of type "text" it needs to
be compared against strings rather then numbers.

The error reported by postgres is:

ERROR:  operator does not exist: text = integer at character 238
No operator matches the given name and argument type(s). You might
need to add explicit type casts.